# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.2.3
maven_group=xyz.thewhitedog9487
archives_base_name=ServerAddressSpaceFix

# Dependencies
fabric_api_version=0.144.0+26.1

compatible_with=26.x

# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=18.0.0-alpha.7

# https://modrinth.com/mod/yacl/versions
# https://maven.isxander.dev/#/releases/dev/isxander/yet-another-config-lib
yacl_version=3.9.0+26.1-fabric

# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok_version=1.18.46